# GA Implementation

Presenting a sample code for the implementation of the GA Algorithm. 
For this, the following procedures will be followed:
- Import of the necessary packages (numpy);
- Prepare the GA operators, including:
    - Function to calculate fitness given a population;
    - Function to select best "n" chromosomes based on best fitness values (Fitness Selection Operator);
    - Function for one point crossover operator;
    - Function for Random Resetting mutation operator;
- Based on these functions, use GA to search for the best parameters for the problem at hand.

In [1]:
# Import of the necessary packages (numpy)
import numpy as np

In [2]:
# Function to calculate fitness given a population
"""
The y=target is to maximize this equation ASAP:
    y = w1.x1 + w2.x2 + w3.x3 + w4.x4 + w5.x5 + 6w.x6
    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)
    What are the best values for the 6 weights w1 to w6?
    We are going to use the genetic algorithm for the best possible values after a number of generations.
"""

def cal_pop_fitness(equation_inputs, pop):
    # Calculating the fitness value of each solution in the current population.
    # The fitness function caulcuates the sum of products between each input and its corresponding weight.
    fitness = np.sum(pop*equation_inputs, axis=1)
    return fitness

In [3]:
# Function to select best "n" chromosomes based on best fitness values (Fitness Selection Operator)
def select_mating_pool(pop, fitness, num_parents):
    # Selecting the best individuals in the current generation as parents for producing the offspring of the next generation.
    parents = np.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = np.where(fitness == np.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

In [4]:
# Function for one point crossover operator;
def crossover(parents, offspring_size):
    offspring = np.empty(offspring_size)
    # The point at which crossover takes place between two parents. Usually it is at the center.
    crossover_point = np.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        # Index of the first parent to mate.
        parent1_idx = k%parents.shape[0]
        # Index of the second parent to mate.
        parent2_idx = (k+1)%parents.shape[0]
        # The new offspring will have its first half of its genes taken from the first parent.
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # The new offspring will have its second half of its genes taken from the second parent.
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

In [5]:
# Function for Random Resetting mutation operator;
def mutation(offspring_crossover):
    # Mutation changes a single gene in each offspring randomly.
    for idx in range(offspring_crossover.shape[0]):
        # The random value to be added to the gene.
        random_value = np.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [6]:
# Based on these functions, use GA to search for the best parameters for the problem at hand.
"""
The y=target is to maximize this equation ASAP:
    y = w1.x1 + w2.x2 + w3.x3 + w4.x4 + w5.x5 + 6w.x6
    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)
    What are the best values for the 6 weights w1 to w6?
    We are going to use the genetic algorithm for the best possible values after a number of generations.
"""

# Inputs of the equation.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

# Number of the weights we are looking to optimize.
num_weights = 6

"""
Genetic algorithm parameters:
    Mating pool size
    Population size
"""
sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.
#Creating the initial population.
new_population = np.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

num_generations = 5
for generation in range(num_generations):
    print("Generation : ", generation)
    # Measing the fitness of each chromosome in the population.
    fitness = cal_pop_fitness(equation_inputs, new_population)

    # Selecting the best parents in the population for mating.
    parents = select_mating_pool(new_population, fitness, 
                                      num_parents_mating)

    # Generating next generation using crossover.
    offspring_crossover = crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # Adding some variations to the offsrping using mutation.
    offspring_mutation = mutation(offspring_crossover)

    # Creating the new population based on the parents and offspring.
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    # The best result in the current iteration.
    print("Best result : ", np.max(np.sum(new_population*equation_inputs, axis=1)))

# Getting the best solution after iterating finishing all generations.
#At first, the fitness is calculated for each solution in the final generation.
fitness = cal_pop_fitness(equation_inputs, new_population)
# Then return the index of that solution corresponding to the best fitness.
best_match_idx = np.where(fitness == np.max(fitness))

print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

[[-1.80368089 -2.84498848  3.00249484  0.34890555  0.45415794  0.09117133]
 [ 3.77237412  2.78100841 -2.29320014  3.94873293  2.42452572  2.65371471]
 [-1.75996461 -1.59945876 -2.77394657 -2.38717362 -3.60599338 -0.90593268]
 [ 0.69189401 -1.85512758  1.38421393 -0.17133017  0.56644921  0.93903357]
 [-1.8123649   2.64725291 -3.26927569  3.51310053 -0.13372757  1.99859726]
 [ 2.6509152   3.2882155   3.64005081 -0.67793882  0.97225495  0.39453661]
 [-2.57970091  1.71092167 -1.97160769 -0.28336226  0.1468505   2.79425724]
 [ 1.62779173  2.18851742  2.33542066  1.51090345  1.96578204 -2.2620965 ]]
Generation :  0
Best result :  59.13722316883941
Generation :  1
Best result :  59.13722316883941
Generation :  2
Best result :  59.13722316883941
Generation :  3
Best result :  61.19651884437302
Generation :  4
Best result :  72.82450410676263
Best solution :  [[[ 2.6509152   3.2882155   3.64005081 -2.38717362 -5.79409827
   -0.90593268]]]
Best solution fitness :  [72.82450411]
